[tool.poetry]
name = "snake_game"
version = "0.1.0"
description = "A simple snake game"
authors = ["QA Engineer <qa@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
